// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeviceSaver is an autogenerated mock type for the DeviceSaver type
type DeviceSaver struct {
	mock.Mock
}

// SaveDevice provides a mock function with given fields: ctx, email, device
func (_m *DeviceSaver) SaveDevice(ctx context.Context, email string, device string) error {
	ret := _m.Called(ctx, email, device)

	if len(ret) == 0 {
		panic("no return value specified for SaveDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceSaver creates a new instance of DeviceSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceSaver {
	mock := &DeviceSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
