// Code generated by mockery v2.46.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DeviceProvider is an autogenerated mock type for the DeviceProvider type
type DeviceProvider struct {
	mock.Mock
}

// Device provides a mock function with given fields: ctx, device, email
func (_m *DeviceProvider) Device(ctx context.Context, device string, email string) error {
	ret := _m.Called(ctx, device, email)

	if len(ret) == 0 {
		panic("no return value specified for Device")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, device, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceProvider creates a new instance of DeviceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceProvider {
	mock := &DeviceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
